### ISSUE TITLE
How to run them offline?

### ISSUE THREAD

**Issue by arel3** [austinvaness/PluginLoader#10]
I'm trying to check out Camera to LCD offline. No internet where I am and I prefer running Space Engineers offline. If you're wondering how I got it: phone. USB file transfer to pc.

I have the loader loading and working but nothing is listed in the plugin menu to select and apply. I have the plugin folder (CameraLCD-main) in Bin64\Plugins. It will not show up to select and apply. What am I not doing or doing incorrectly?

**Comment by arel3** [comment]
Update: I've learned through Steam forums others that use plugins for Space Engineers said the plugins auto generate when they have an internet connection. I don't have an internet connection. Is there no way to load and run them locally? If there is please explain how.

I am not on and will not be on discord. Please answer here.

**Comment by austinvaness** [comment]
You need to put *.dll files in the Plugins folder. They will show up as local plugins in the list then. Camera LCD is pretty buggy right now so be prepared for that. Here is the compiled version of CameraLCD: [CameraLCD.zip](https://github.com/austinvaness/PluginLoader/files/7576896/CameraLCD.zip) After extracting it you will need to unblock it in the file properties.

**Comment by austinvaness** [comment]
Also, you will find downloads of GitHub software on the Releases page. CameraLCD doesnt have any releases so thats why im linking it here. It sounds like you downloaded the source code.

**Comment by arel3** [comment]
Thanks a lot! I'll try this out. I know it's buggy to your standards. Others said it works well. I guess it is the source code I have. Has a gui, patch, properties and wrapper folder in the archive. 
Thanks again! I'll let you know how it goes, I'll close this issue report if it works. Thanks again!

**Comment by arel3** [comment]
Works and it's ab

**Comment by arel3** [comment]
Works and it's absolutely awesome! I'll be testing it out real good to see what it cab and can't do

**Comment by arel3** [comment]
Works and it's awesome! Thank you so much for doing this! All of it. I haven't seen any bugs so far but I did try to use it at a station to view a camera on a satellite in space. That didn't work, I wasn't really expecting it to through an antenna on a disconnected grid. If that's possible please put it in your suggestion box.

If this works as a previous version I saw featured on a youtube where if it's set up on a drone connected it continues to work with the drone disconnected I'll rebuild the satellites and try that. 

Awesome work! Can't give enough thanks!

**Comment by viktor-ferenczi** [comment]
**Precompiled plugins for offline use:**

Download the ZIP from OneDrive:
https://1drv.ms/u/s!AqEgz8G_d8TSh8Nzj0Doy6uASqdoiA?e=mulFf8

See the installation instructions in the ZIP file.

Works with game version 1.199.025 with plugins as of 2021-11-24.

Updated packages may be released by me after major game updates, once most of the plugins fixed.

Disclaimer: The DLLs were compiled on my machine. Use only at your own risk.
