### ISSUE TITLE
 PluginLoader.dll

### ISSUE THREAD

**Issue by lego5810** [austinvaness/PluginLoader#4]
im unable to find  PluginLoader.dll in the files

**Comment by austinvaness** [comment]
Did you download the zip file starting with "PluginLoader-" from the releases page?

**Comment by Agentwash121** [comment]
cant find pluginloader.dll. can only see pluginloader.sln

**Comment by screwballl** [comment]
With the redesign of github, there is no "releases" page, only code. The list of files shows no dll files that can be downloaded.

**Comment by viktor-ferenczi** [comment]
![image](https://user-images.githubusercontent.com/1848514/132073423-2c678b6c-268e-43da-9dfe-d4fae08644d2.png)

**Comment by screwballl** [comment]
Thank you for that info. 

Next, there is no Bin64 folder for a steamcmd server setup. Attempted the dll files with the rest of the dll files under X:\steamcmd\spaceeng\DedicatedServer64 but it displays this error. Do you know what the steamcmd alternate folder location would be?
![image](https://user-images.githubusercontent.com/7374917/132075216-555e87c5-739f-46c8-a754-40b9f679b023.png)

**Comment by austinvaness** [comment]
You can't use Plugin Loader on dedicated servers. That is totally outside the use case of this program because servers have their own plugin system and no in game gui.

**Comment by screwballl** [comment]
understood, thank you for your help
